config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', locale: "en"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :doctors do
      resources :reviews
    end

    resources :users
     
    resources :filters
   
    resources :articles

    resources :searches

    resources :appointments

    resources :time_slots

    resources :jakartas

    get "abouts/show"

    get "contacts/show"
    post "contacts/send_message"

    get "privacy_policies/show"
   
    
    root 'jakartas#index'

    #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    #match 'auth/failure', to: redirect('/'), via: [:get, :post]
    #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

    #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    #match 'auth/failure', to: redirect('/'), via: [:get, :post]
    #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  end
  
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category

	has_attached_file :article_img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png" 
	validates_attachment_content_type :article_img, content_type: /\Aimage\/.*\Z/

	def self.search_articles(filter)
		if filter
			where(["title LIKE ?", "%#{filter}%"])
			# where(["created_at LIKE ?", date]) if created_at.present?
		    # where(["category_id LIKE ?", category_id]) if category_id.present?
			# where(["view ?", view])if view.present?
		else
			all.order('created_at DESC')
		end
	end

	# def search_articles
	# 	articles = articles.all.order('created_at DESC')
	# 	articles = articles.where(["created_at LIKE ?", date]) if created_at.present?
	# 	articles = articles.where(["category_id LIKE ?", category])if category_id.present?
	# 	articles = articles.where(["view ?", view])if view.present?

	# 	return articles
	# end

	RailsAdmin.config do |config|
		config.model 'Article' do

			# Create fields
			create do 
				field :article_img 
				field :title
				field :description
				field :category_id
				field :created_at
				field :updated_at
				
			end

			# Edit fields
			edit do 
				field :article_img
				field :title
				field :description
				field :category_id
				field :created_at
				field :updated_at
			
			end

			# Show fields
			list do 
				field :article_img
				field :title
				field :description
				field :category_id
				field :created_at
				field :updated_at
				
			end
		end
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :find_article, only: [:show, :edit, :update, :destroy]

	def index
		# @article = Article.all.order('created_at DESC')
		# @article = Article.where("category_id = '3'")
		# @cat1 = Article.where(category_id: 1).last(1)
		# @cat2 = Article.where(category_id: 2).last(1)
		# @cat3 = Article.where(category_id: 3).last(1)

		# @article = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
		# @articleTotal = Article.count
		# @articlePage = @articleTotal % 2
		# @categories = Category.all.map{ |c| [c.name, c.id]}

		# if params[:category].blank?
		# 	@article = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
		# else
		#  	@category_id = Category.find_by(name: params[:category]).id
		#  	@article = Article.where(:category_id => @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 2)
		# end
		
		# @articleTotal = Article.count
		# @articlePage = @articleTotal % 2
		# @category = Category.all
		#@categories = Category.all.map{ |c| [c.name, c.id]}

		# if params[:search].blank?
		# 	@article = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
		# else
		# 	@article = Article.where(["title LIKE ?", "%#{params[:search]}%"]).paginate(page: params[:page], per_page: 2)	
		# end

		@article  = Article.search_articles(params[:filter]).paginate(page: params[:page], per_page: 3)

		@article1 = Article.where(:category_name => 'diet').paginate(page: params[:page], per_page: 1)
		@article2 = Article.where(:category_name => 'healthy').paginate(page: params[:page], per_page: 1)
		@article3 = Article.where(:category_name => 'news').paginate(page: params[:page], per_page: 1)
		
		@category = Article.uniq.pluck(:category_name)
		@date     = Article.all
		@doctor   = Doctor.all

	end

	def show
	end

	def new
		@article = Article.new
		@category = Category.new

	end

	def create
		@article = Article.new(article_params)
	end

	def update

	end

	def edit
	end

	def destroy
	end

	private
		def article_params
			params.require(:article).permit(:category_id)
		end

		def find_article
			@article = Article.find(params[:id])
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_tag articles_path, :method => 'get' do%>

	<select name="created_at">
      <%= @date.each do |a| %>
      	<option value="<%= a.created_at %>"><%= a.created_at.strftime("%B") %></option>
      <% end %>
  	</select>
	<select name="category_id">
      <%= @category.each do |c| %>
      	<option value="<%= c %>"><%= c %></option>
      <% end %>
  	</select>
  	<select name="view">
      	<option value=view_1>Most Viewed</option>
     	<option value=view_2>Least Viewed</option>
  	</select>
	<%= submit_tag "Search", :class => "btn go float-left"%>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit Info</h2>

<%= simple_form_for @article do |f|%>
	<%= f.file_field :article_img %> 

	<%= f.button :submit %>
<% end %>

app/views/articles/index.html.erb
            <main class="main-content">
                <section class="section-content healthier-lifestyle bg-healthier-lifestyle decode-size">
                    <div class="wrapper42">
                        <div class="healthier-lifestyle-content text-center">
                            <h1>For a healthier lifestyle.</h1>
                            <span>Find a doctor who can help you<br> prevent certain illnesses</span>
                        </div>
                       <!-- <div class="form-find text-center">
                            <form>
                                <input type="text" name="Name of Doctor" placeholder="Name of Doctor">
                                <select>
                                    <option value="">City/Province</option>
                                </select>
                                <select>
                                    <option value="">Specialty</option>
                                </select>
                                <input type="submit" value="find" class="btn find">
                            </form>
                        </div>-->
                        <div class="form-find-doctor">
                        <ul>
                            <li>
                               <input type="text" name="Name of Doctor" placeholder="Name of Doctor">
                            </li>
                            <li>
                                <select>
                                    <option value="">City/Province</option>
                                </select>
                            </li>
                            <li>
                               <select>
                                    <option value="">Specialty</option>
                                </select>
                            </li>
                            <li>
                               <input type="submit" value="find" class="btn find">
                            </li>
                        </ul>
                        </div>

                    </div>
                </section>

                <section class="section-content article-list">
                    <div class="wrapper42">
                        <h2>Latest News</h2>
                        
                        <div class="article-list-content ">
                            <ul>
                                <% @article1.each do |article| %>
                                <li>
                                    <figure>
                                        <label>Diet</label>
                                         <%= image_tag article.article_img %>
                                    </figure>
                                    <span><%= article.created_at.strftime("%B, %d, %Y")  %></span>
                                    <h2><%= article.title %><h2>
                                    <p><%= article.description %>
                                        <a href="#">Read More</a>
                                    </p>
                                </li>
                               <div class="clear"></div>
                               <% end %>
                            </ul>

                             <ul>
                                <% @article3.each do |article| %>
                                <li>
                                    <figure>
                                         <label>News</label> 
                                         <%= image_tag article.article_img %>
                                    </figure>
                                    <span><%= article.created_at.strftime("%B, %d, %Y")  %></span>
                                    <h2><%= article.title %><h2>
                                    <p><%= article.description %>
                                        <a href="#">Read More</a>
                                    </p>
                                </li>
                               <div class="clear"></div>
                               <% end %>
                            </ul>

                            <div class="pagination">
                                <%= link_to "< Previous ", params.merge(:page => @article.previous_page) %>
                                <%= link_to "More Articles > ", params.merge(:page => @article.next_page) %>
                            </div>
                            <div class="text-center">
                          <!--   <% if @article.previous_page %>
                                <% link_to "< Previous ", params.merge(:page => @article.previous_page) %>
                            <% end %> -->
                            <!--<div  class="flickr_pagination">
                                <span class="btn article-list"><%= link_to "< Previous ", params.merge(:page => @article.previous_page) %></span>
                                <span class="btn article-list">Page <%= @article.current_page %> of <%= @article.total_pages %></span>
                                <span class="btn article-list"><%= link_to "More Articles > ", params.merge(:page => @article.next_page) %></span>
                            </div>-->
                               <!--  <a href="#" class="btn article-list">Previous</a>
                                <a href="#" class="btn article-list">More Articles</a> -->
                            </div>
                        </div>
                        <aside class="side-bar article-list">
                            <div class="articless">
                            <ul>
                                <% @article2.each do |article| %>
                                <li>
                                    <figure>
                                         <label class="healthylabel">Healthy Tips</label> 
                                         <%= image_tag article.article_img %>
                                    </figure>
                                    <span><%= article.created_at.strftime("%B, %d, %Y")  %></span>
                                    <h2><%= article.title %><h2>
                                    <p><%= article.description %>
                                        <a href="#">Read More</a>
                                    </p>
                                </li>
                               <% end %>
                            </ul>
                            </div>
                         
                            <div class="form-filter">
                                <span>Filter by:</span>
                                <%= render 'form' %>
                               <!--  <form>
                                    <select>
                                        <option>Date</option>
                                    </select>
                                    <select>
                                        <option>Category</option>
                                    </select>
                                    <select>
                                        <option>Popularity</option>
                                    </select>
                                    <input type="submit" name="go" value="go" class="btn go float-right">
                                    <div class="clear"></div>
                                </form> -->
                                
                            
                            </div>
                            <div class="clear"></div>
                        </aside>
                        <div class="clear"></div>
                    </div>
                    
                </section>
            </main>
            <script>
            $(function() {

              // $(window).scroll(function() {
              //       if( $(window).scrollTop() > 0)
              //           $('.main-header').css('background', 'rgba(255,255,255,1)');
              //       else
              //           $('.main-header').css('background', 'rgba(255,255,255,0.7)');
              //   });

                $('.tab-links.nav ul li a').on("click", function (e){
                    e.preventDefault(); 
                    $('.tab-links.nav ul li a.active').removeClass('active');
                    $(this).addClass('active');
                    $('.tab-content.nav.active').removeClass('active');
                    $(this.rel).addClass('active');
                });

            });
        </script>