config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', locale: "en"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :doctors do
      resources :reviews
    end

    resources :users
     
    resources :filters
   
    resources :articles

    resources :searches

    resources :appointments

    resources :time_slots

    resources :jakartas

    get "abouts/show"

    get "contacts/show"
    post "contacts/send_message"

    get "privacy_policies/show"
   
    
    root 'jakartas#index'

    #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    #match 'auth/failure', to: redirect('/'), via: [:get, :post]
    #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

    #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    #match 'auth/failure', to: redirect('/'), via: [:get, :post]
    #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  end
  
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def show
	end

	def send_message
		data = params[:email]
		if data[:name].nil? || data[:email].nil? || data[:message].nil?
			redirect_to :back
			flash[:notice]='Please fill all the fields'
		else
			@name = data[:name]
			@email = data[:email]
			@message = data[:message]
			ContactMailer.send_message(@name, @email, @message).deliver_now
			redirect_to contacts_show_path
		end
	end

end

app/views/contacts/show.html.erb
<!-- Main Content -->
<main class="main-content">
    <!-- Banner -->
    <section class="banner bg-banner-contact text-center">
        <div class="wrapper">
            <h1>
                Better health tracking
                <br>starts today!
            </h1>
        </div>
    </section>

    <!-- Section -->
    <section class="section-content bg-dark-blue text-center">
        <div class="wrapper">

            <h3 class="contactusleft"> Contact Us</h3>
            <div class="contacthr"> </div>

            <div class="pure-g">

                <!-- 1st column -->
                
                <div class="pure-u-1-2 contact1">
                    <%= form_for :email, url: contacts_send_message_path do |f| %>
                    <b class="white">Name</b><br>
                    <%= f.text_field :name %><br/>

                    <b class="white">Email</b><br>
                    <%= f.text_field :email %><br/>

                    <b class="white lineheight">Your Message</b><br>
                    <%= f.text_area :message, class: 'customtextarea' %>
                    <br>
                    <%= f.submit 'SEND',class: 'buttonsend' %>
                    <% end %>
                </div>
                

                <!-- 2nd Column -->
                <div class="pure-u-1-2 contact2">
                    <div class="readypadd">
                        <b>Ready for a healthier<br> lifestyle? Join us!</b>
                    </div>

                    <div class="readypadd">
                        <span>-Neque porro quisquam est qui dolorem ipsum quia  , </span><br>
                        <span>-Neque porro quisquam est qui dolorem ipsum quia , </span><br>
                        <span>-Neque porro quisquam est qui dolorem ipsum quia , </span>

                    </div>
                </div>
            </div>


        </div>
    </section>
</main>